import { useState } from 'react'
import type { IconName } from './icons'
import { Icon } from './icons'
import { classes } from './utils'
import { MenuAvatar } from './menu-avatar'
import type { PlayerPosition } from './profile-avatar'

export type SidebarItem = { id: string; label: string; icon: IconName; href?: string; children?: SidebarItem[] }
export type SidebarUser = { name: string; detail?: string; avatar?: string; guest?: boolean; position?: PlayerPosition }
export function Sidebar({ items, systemName = 'Convocado FC', version = 'v0.1.0', user = { name: 'Convidado', detail: 'Acesso público', guest: true }, team = 'Meu time', search, onSearch, onSignOut, onSwitchProfile, onSwitchTeam }: { items: SidebarItem[]; systemName?: string; version?: string; user?: SidebarUser; team?: string; search?: string; onSearch?: (value: string) => void; onSignOut?: () => void; onSwitchProfile?: () => void; onSwitchTeam?: () => void }) {
  const [collapsed, setCollapsed] = useState(false); const [open, setOpen] = useState<string[]>([]); const toggle = (id: string) => setOpen((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id])
  return <aside className={classes('ui-sidebar', collapsed && 'ui-sidebar--collapsed')}><div className="ui-sidebar__brand"><span className="ui-sidebar__logo"><Icon name="bola" size={22} /></span><span className="ui-sidebar__brand-copy"><strong>{systemName}</strong><small>{version}</small></span><button aria-label={collapsed ? 'Expandir menu' : 'Recolher menu'} className="ui-sidebar__toggle" onClick={() => setCollapsed(!collapsed)} type="button"><Icon name={collapsed ? 'bola' : 'menu'} size={20} /></button></div><div className="ui-sidebar__switchers"><button className="ui-sidebar__switcher" onClick={onSwitchTeam} type="button"><Icon name="times" size={17} /><span><small>Time atual</small><strong>{team}</strong></span><Icon name="chevron-down" size={15} /></button><button className="ui-sidebar__switcher" onClick={onSwitchProfile} type="button"><Icon name="gerenciar" size={17} /><span><small>Perfil</small><strong>{user.guest ? 'Convidado' : 'Administrador'}</strong></span><Icon name="chevron-down" size={15} /></button></div><nav aria-label="Menu principal" className="ui-sidebar__nav">{onSearch && <label className="ui-sidebar__search"><Icon name="pesquisar" size={16} /><input aria-label="Buscar no menu" onChange={(event) => onSearch(event.target.value)} placeholder="Buscar no menu" type="search" value={search ?? ''} /></label>}{items.map((item) => <SidebarLink item={item} key={item.id} open={open.includes(item.id)} onToggle={toggle} />)}</nav><div className="ui-sidebar__account"><MenuAvatar imageUrl={user.avatar} name={user.name} position={user.position} size="sm" /><div className="ui-sidebar__user"><strong>{user.name}</strong><small>{user.detail ?? (user.guest ? 'Entre para continuar' : 'Usuário conectado')}</small></div>{onSignOut && <button aria-label={user.guest ? 'Entrar' : 'Sair'} className="ui-sidebar__logout" onClick={onSignOut} type="button"><Icon name={user.guest ? 'entrar' : 'sair'} size={18} /><Icon className="ui-sidebar__logout-system" name="bola" size={18} /></button>}</div></aside>
}
function SidebarLink({ item, open, onToggle }: { item: SidebarItem; open: boolean; onToggle: (id: string) => void }) { const content = <><Icon aria-hidden="true" name={item.icon} size={18} /><span>{item.label}</span>{item.children && <Icon className="ui-sidebar__chevron" name="chevron-down" size={15} />}</>; return <div className="ui-sidebar__item">{item.children ? <button aria-expanded={open} className={classes('ui-sidebar__link', open && 'is-open')} onClick={() => onToggle(item.id)} type="button">{content}</button> : <a className="ui-sidebar__link" href={item.href ?? '#'}>{content}</a>}{item.children && open && <div className="ui-sidebar__submenu">{item.children.map((child) => <a href={child.href ?? '#'} key={child.id}><Icon name={child.icon} size={15} /><span>{child.label}</span></a>)}</div>}</div> }
